# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf240aabcbe65cde8ba61b87ede99ac30d84fa7fa8e76e6439502c6376cdbea0a09cc9346764a67ec59f362250dbf6ddf5ff05f0a72ad8601cb6aa86ede43fec

test:
  secret_key_base: ce00ff2596498dedf29425a08bf1784b0751bae80f83e7496222a676a857b40668ff5516494ebf45cf6f055d831f78d4a74f8a60b518b16f6414bede1ff41dcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
